print("Task 1:")
print("\t --- \n \t/\t\\\n   /\t \\\n   |\t |\t\n   |\t |\t\n   |\t |\t\n   \\\t /\n\t\\   /\n\t --- ")
print("\nTask 2:")
print('"To be\n\t\tor not\n\t\t\t\tto be!"\n\t\t\t\t\t\t/Shakespeare/')
print("\nTask 3:")
print("\\'\t  Single Quote\n\\\\\t  Backslash\n\\n\t  New Line\n\\r\t  Carriage Return\n\\t\t  Tab\n\\b\t  Backspace\n\\\"\t  Double Quotation Mark \"\n\\\'\t  Single Quotation Mark \'")
print("\nTask 4:")
print("*\t\t* \t  * \t*\t*\t\t*\t  * * * * *\t\t *\n* * \t* \t  * \t*  *\t\t*\t\t  *\t\t   *   *\n*   *   *\t  *\t\t* *   \t\t*\t\t  *\t\t  *******\n*\t  * *\t  *\t\t*  *  \t\t*\t\t  *\t\t *\t\t *\n*\t\t*\t  *\t\t*   *\t\t*\t\t  *\t\t*\t\t  *")
print("\nTask 5:")
print("\" '\\t', '\\n', '\\\\', '\\'', '\\\"' \"")

